# Generated by Django 2.2.2 on 2019-06-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('ingame_name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('team', models.CharField(max_length=30)),
                ('race', models.CharField(max_length=30)),
            ],
        ),
    ]
